x + 10		# => x.+(10)

x
  + 10		# => x.+(10)

x
+ 10		# => parse error

  x
+ 10		# => parse error

x +
  10		# => x.+(10)

x +
10			# => parse error

(
x + 10
)		# => x.+(10)

(
  x + 10
)		# => x.+(10)

(
x
  + 10
)		# => x.+(10)

(
x
+ 10 
)			# => x.+(10)

(
  x
+ 10 
)			# => x.+(10)

(
x +
  10
)			# => x.+(10)

(
x +
10
)			# => x.+(10)

(
  x +
  10
)			# => x.+(10)

(
  x +
10
)			# => x.+(10)
