i := 10 * -(2 + 3)
if i == -50
  j := i // 3
  unless i == -50
    "NG"
    "NG"
  else if j == -17
    "OK"
    "OK"
  else unless j == -16
    for x in 10
      "NG"
      "NG"
    "NG"
  else
    while true
      "NG"
      "NG"
    else
      "NG"
      "NG"
      "NG"
  j + 2
i + 2
